### ISSUE TITLE
Failed to compile in latest kernel 6.12

### ISSUE THREAD

**Issue by ashraddhansh** [PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux#15]
`sudo ./install_driver.sh `

```
### Module For QUANT HD USER FACING BY @Prabhat_Proxy ###
     Special Thanks to Giuliano69 for the driver :)

building

make: Entering directory '/usr/lib/modules/6.12.1-zen1-1-zen/build'
  CC [M]  /home/Tomato/Clone/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/uvc_driver.o
/home/Tomato/Clone/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/uvc_driver.c:22:10: fatal error: asm/unaligned.h: No such file or directory
   22 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:229: /home/Tomato/Clone/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc/uvc_driver.o] Error 1
make[1]: *** [/usr/lib/modules/6.12.1-zen1-1-zen/build/Makefile:1934: /home/Tomato/Clone/Quanta-HD-User-Facing-0x0408-0x4035_linux/src/uvc] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/lib/modules/6.12.1-zen1-1-zen/build'
failed to compile module! check docs and report any error

report any issue on github repo https://github.com/PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux/issues 
```

**Comment by fus0g** [comment]
which distribution?

**Comment by ashraddhansh** [comment]
Arch Linux. The strange thing is the camera is still working.

**Comment by fus0g** [comment]
😂
